// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8SOCG0dJAn1H-MbDY5J2-hDEmubiszi4',
    appId: '1:602753054721:web:8150821789e41989566800',
    messagingSenderId: '602753054721',
    projectId: 'chattie-ae098',
    authDomain: 'chattie-ae098.firebaseapp.com',
    storageBucket: 'chattie-ae098.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Nk4lGcJBtmAChTTFOE3uqJQhR5ijWu0',
    appId: '1:602753054721:android:6a517b421ff269e1566800',
    messagingSenderId: '602753054721',
    projectId: 'chattie-ae098',
    storageBucket: 'chattie-ae098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApVDkWJxvZmUs4Z0BWs9Ef9klrZrd_lyc',
    appId: '1:602753054721:ios:534519b33b4bf26b566800',
    messagingSenderId: '602753054721',
    projectId: 'chattie-ae098',
    storageBucket: 'chattie-ae098.appspot.com',
    iosClientId: '602753054721-btc32ujdgis2dij0e48eamjrcs7cle5k.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
